### ISSUE TITLE
Different product name for customs declaration

### ISSUE THREAD

**Issue by manureini** [vendidero/woocommerce-germanized-dhl#13]
Hello ;)

I have a use case, that the product item name should be replaced with another name for the customs declaration.
For example, when selling art, we use the design as the product name. But we would like to have the customs declaration say "Art piece" instead of the design name.

Right now I know two solutions so solve this issue:

- Add a filter for the result of this function:
https://github.com/vendidero/woocommerce-germanized-dhl/blob/1cbfeab9c10b9eb96bf9f71db889bf5215d95c19/includes/wc-gzd-dhl-core-functions.php#L39
(The $shipping should be passed so I can provide a custom mapping from Woocommerce Product to string)

- Create a custom ShipmentItem class
https://github.com/vendidero/woocommerce-germanized-shipments/blob/2146ed82952cc0215ecc87fae3b4cbd8ebcdd99f/src/ShipmentItem.php#L14

Can you recommend a solution?

**Comment by dennisnissle** [comment]
Hi there,

I guess a filter would be the way to go. I've added a filter here:
https://github.com/vendidero/woocommerce-germanized-dhl/commit/f9f63293818872f89c9b68b1837406139a5b3004

Cheers

**Comment by manureini** [comment]
Thank you very much!
