### ISSUE TITLE
Custom customerReference in dal_label_body

### ISSUE THREAD

**Issue by thunermay** [vendidero/woocommerce-germanized-dhl#20]
Hi,

I want to be more productive and give our employees in the shipment division an easier job.
I just hand them the shipping labels but have to write manually on them what is ordered.
There is an option in the label from dhl to set the customerReference, which is now "Sendung #Sendungsnummer zur Bestellung Bestellnummer". I saw in the code in Labelsoup.php that it is hardcoded. Is it possible to change that so you can make it variable? It would be a huuuge improvement in our workflow!

Thanks in advance!

**Comment by dennisnissle** [comment]
Hi there,

a filter for that purpose exists here: https://github.com/vendidero/woocommerce-germanized-dhl/blob/master/includes/wc-gzd-dhl-core-functions.php#L297

You may use this filter to adjust the reference to your own needs.

Cheers

**Comment by thunermay** [comment]
How do I use the filter? Like concrete ways to do it. Im fairly new to WordPress so I don't know much about it.
Thanks

**Comment by dennisnissle** [comment]
An example can be found here: https://gist.github.com/vendidero/4985a50f9790655fad03567ac627fd29
You may need help from a PHP developer with customizing it to your needs.

**Comment by thunermay** [comment]
Thanks for the example! I figured out how the add_filter() method works. The question is how I get the specific items that where ordered? Like how many of book xyz or how many cards xyz. I think the `$label` and `$shipment` are the objects. Defined in `WooCommerce-germanized-dhl` for the `label` and `WooCommerce-germanized-shipments` for the `$shipment`. But I haven't found a documentation for what is in the `$shipment`. I think I don't need the `$label` but I for sure need the `$shipment`. 
I would be glad if you could answer me this.
PS: In which file do I add the `add_filter` method?

**Comment by dennisnissle** [comment]
Sorry but we are not able to replace a web dev for you - please consider seeking professional help from a WordPress/Woo dev. You could check the vars via `var_dump` for example. The shipment implementation may be found here: https://github.com/vendidero/woocommerce-germanized-shipments/blob/master/src/Shipment.php

The add_filter call may be added to your functions.php of your child theme or to a custom plugin.

Cheers

**Comment by thunermay** [comment]
Hey, I got the filter set up but I can't access the items getting from the `$shipment`-object.
```
function addItemsToLabelReference($ref, $label, $shipment ) {
    //clear the ref that is passed to the filter
    $ref = "";

    //do for every item in the shipment
	foreach($shipment->get_items() as $item){
	    //append SKU and quantity
	    $ref = $ref . $item->get_sku() . $item->get_quantity() . ",";
	}
    return $ref;
}
```

The `get_items` is no problem but when I try to access the `sku` or the `quantity` the page crashes. I'm afraid I can't enable logs. Is there anything I've done wrong? Or can you tell me how I can call the functions?

Thanks

**Comment by thunermay** [comment]
I figured the issue out. Closing the issue
