### ISSUE TITLE
DHL Label - Retoure - Kein Empfänger auswählbar part2

### ISSUE THREAD

**Issue by hberke01** [vendidero/woocommerce-germanized-dhl#37]
https://github.com/vendidero/woocommerce-germanized-dhl/issues/23#issuecomment-947428381

Hallo liebe Profis, ich frage zu obigem Thema nach Hilfe.

Der obige Link behandelt ein vermutlich identisches Problem, welches nun ich habe.
Leider finde ich unter der verlinkten Anleitung keine Lösung.

Mein Problem: 
Germanized hinterlegt offenbar keine Adresse des Empfängers der Retoure. 
Unter 
Germanized-Versanddienstleister-DHL-Labels
habe ich keine Einträge IDs hinterlegt.

Unter
Germanized-Sendungen-Adressen
habe ich eine Retoure-Adresse  hinterlegt. 

Leider gibt germanized aber den Fehler:

"Empfänger fehlt oder existiert nicht"

nachdem ich aus einer nicht auswählbaren Liste wählen sollte.

Ein Eintrag mit einer ID unter "Labels", hat leider nichts ergeben.

Also: Was mache ich hier falsch?

Es wäre klasse, falls mir jemand helfen könnte und bin für jede Hilfe wirklich dankbar. Gern auch eben mit dem Verweis auf eine bestehende Dokumentation.

**Comment by dennisnissle** [comment]
Hi,

die Empfänger-IDs in den Label-Einstellungen für die Retoure sind verpflichtend. Ohne Empfänger wird es nicht funktionieren. S.a.: https://vendidero.de/dokument/dhl-integration-einrichten#retoure

Wende dich im Zweifel bitte an unseren wp.org Support:
https://wordpress.org/support/plugin/woocommerce-germanized/

Die GitHub Issues sind hier eher für die (Weiter-) Entwicklung des Plugins gedacht.

Grüße
